version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    networks:
      - proxyNet
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /data/docker//volumes/deluge/config:/config
      - /data/docker//volumes/deluge/downloads:/downloads
    restart: unless-stopped

networks:
    proxyNet:
      name: SWAG Proxy