version: '2.1'
services:
  mongodb:
    image: mongo:4.2
    container_name: graylog_mongodb
    networks:
      - graylogInternal
    volumes:
      - /dockerCompose/volumes/graylog/mongodb:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: graylog_elasticsearch
    networks:
      - graylogInternal
    environment:
#      - network.host=0.0.0.0
#      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISCOVERY.TYPE=single-node
    volumes:
      - /dockerCompose/volumes/graylog/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    networks:
      - proxyNet
      - graylogInternal
    volumes:
      - /dockerCompose/volumes/graylog/graylog:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      #- GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      #- GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog_elasticsearch:9200
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
#      - 1514:1514
      # Syslog UDP
#      - 1514:1514/udp
      # GELF TCP
#      - 12201:12201
      # GELF UDP
#      - 12201:12201/udp

networks:
    proxyNet:
      name: SWAG Proxy
    graylogInternal:
      name: Graylog Internal Network