version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    networks:
      - proxyNet
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /data/docker//volumes/heimdall:/config
    restart: unless-stopped

networks:
    proxyNet:
      name: SWAG Proxy