version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    network_mode: "bridge"
    networks:
      - proxyNet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /dockerCompose/volumes/heimdall/config:/config
    restart: unless-stopped

networks:
    proxyNet:
      name: SWAG Proxy