version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    networks:
      - proxyNet
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
      - URL=h4rb.bid
      - SUBDOMAINS=u
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= rzicMLwJTSxW5eAJ
    volumes:
      - /data/docker/volumes/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped


networks:
    proxyNet:
      name: SWAG Proxy